
POST http://localhost:8080/events
Content-Type: application/json

{
  "title": "my event 4",
  "details": "my event fake description",
  "maximumAttendees": 4
}

###
GET http://localhost:8080/events/d05067e8-4b1b-48ab-8d44-ad9e12350815

###
GET http://localhost:8080/events/d05067e8-4b1b-48ab-8d44-ad9e12350815/attendees

###
POST http://localhost:8080/events/d05067e8-4b1b-48ab-8d44-ad9e12350815/attendees
Content-Type: application/json

{
  "name": "john doe 7",
  "email": "johndoe7@example.com"
}

###
GET http://localhost:8080/attendees/2080570a-38dd-48f8-93cf-ad99edb16af3

###
GET http://localhost:8080/attendees/2080570a-38dd-48f8-93cf-ad99edb16af3/check-in