
POST http://localhost:8080/events
Content-Type: application/json

{
  "title": "my event 4",
  "details": "my event fake description",
  "maximumAttendees": 4
}

###
GET http://localhost:8080/events/d05067e8-4b1b-48ab-8d44-ad9e12350815

###
GET http://localhost:8080/events/d05067e8-4b1b-48ab-8d44-ad9e12350815/attendees
